repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: dart-fix
        name: dart-fix
        entry: bash -c 'dart fix --apply'
        language: system
        type: [ dart ]
        files: lib/.*\.dart$

      - id: flutter-test
        name: flutter-test
        entry: bash -c 'flutter test'
        language: system
        type: [ dart ]
