include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - require_trailing_commas
