name: withu
description: "Withu mobile application"

version: 1.0.0+7

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Dependency Injection
  get_it: 8.0.0

  # Being able to compare objects in Dart
  equatable: ^2.0.5

  # Fetch Data From Api
  dio: 5.7.0
  pretty_dio_logger: ^1.4.0

  # Logging Interceptor
  logging: 1.2.0

  # BloC State Management
  flutter_bloc: 8.1.6

  # Json Annotation
  json_annotation: 4.9.0

  # Code generation
  freezed_annotation: 2.4.4

  # Router
  auto_route: 9.2.2

  # Logging
  logger: ^2.4.0

  # Localization
  intl: ^0.19.0
  easy_localization: ^3.0.7

  # Test Mocking
  mockito: ^5.4.4

  # api mocking
  http_mock_adapter: ^0.6.1

  # widget related packages
  infinite_scroll_pagination: ^4.0.0
  calendar_date_picker2: ^1.1.7
  flutter_keyboard_visibility: ^6.0.0

  # Local Database
  shared_preferences: ^2.3.2

  # Test Mocking
  mocktail: ^1.0.4

  # firebase
  firebase_core: ^3.12.0
  firebase_analytics: ^11.4.3
  firebase_messaging: ^15.2.3
  firebase_crashlytics: ^4.3.4
  google_fonts: ^6.2.1
  toastification: ^3.0.1
  url_launcher: ^6.3.1
  sign_in_with_apple: ^6.1.4
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # build related
  build_runner: 2.4.12
  json_serializable: 6.8.0
  freezed: 2.5.7

  # lint
  flutter_lints: ^5.0.0

  # router
  auto_route_generator: ^9.0.0

  # Resource manager
  flutter_gen_runner:

  # Svg
  flutter_svg:

  # Bloc test
  test: ^1.25.7
  bloc_test: ^9.1.7

  # App Icon
  flutter_launcher_icons: "^0.14.3"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

# Derry script manager
scripts:
  # build runner 실행
  build: flutter pub run build_runner build --delete-conflicting-outputs

  abb: flutter build appbundle --release --flavor prod -t lib/core/config/env/prod.dart --no-tree-shake-icons

  ios: flutter build ios --release --flavor prod -t lib/core/config/env/prod.dart --no-tree-shake-icons

  # 전체 파일 대상으로 pre-commit hooks 스크립트 실행
  pre-commit: pre-commit run --all-files

  # android keychain sha-1
  sha1: keytool -list -v -alias upload -keystore ./android/app/keystore/upload-keystore.jks

  # App Icon 생성
  gen-icons: dart run flutter_launcher_icons


# Resource manager
flutter_gen:
  output: lib/gen/
  line_length: 80

  # Optional
  integrations:
    image: true
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: "assets/images/app_icon.png"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 24
