# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

project 'Runner', {
  'Profile-dev' => :release,
  'Debug-dev' => :debug,
  'Debug-prod' => :debug,
  'Release-dev' => :release,
  'Release-prod' => :release,
}
target 'Runner' do
  use_frameworks!

  target 'RunnerTests' do
    inherit! :search_paths
  end
end
