default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :deploy do

    setup_ci

    # 2중 인증 대신 접근 권한 설정
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_KEY_CONTENT"],  #
      is_key_content_base64: true,
      duration: 1200,
      in_house: false
    )

    match(
      type: "appstore",
      api_key: api_key
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "prod",
      clean: true,
    )

    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,  # 심사 자동 제출
      automatic_release: false,  # 승인 시 자동 출시
      precheck_include_in_app_purchases: false,
    )
  end
end
