
default_platform(:android)

# 환경변수 설정
ANDROID_JSON_KEY=Base64.decode64(ENV["ANDROID_JSON_KEY"])

platform :android do
  desc "Android 프로덕션 빌드 및 플레이스토어 배포"
  lane :deploy do

    # 트랙 설정 (internal, alpha, beta, production)
    track = "internal"

    # 플레이스토어 업로드
    upload_to_play_store(
      track: track,
      aab: "../build/app/outputs/bundle/prodRelease/app-prod-release.aab",
      release_status: "draft", # draft로 설정하여 수동 검토 후 출시
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      json_key_data: "#{ANDROID_JSON_KEY}"
    )
  end
end
