name: F-Lab flutter-withu Prod Deploy

on:
  push:
    branches: [ feature/ci-cd ]

# 동시성 설정 추가
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_prod:
    runs-on: macos-latest
    steps:
      # 기본 저장소 체크아웃
      - name: Clone repository
        uses: actions/checkout@v4

      # Brew 설정
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      # Java 17 설정
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # fastlane 설치
      - name: Install Fastlane
        run: brew install fastlane

      # Flutter 설정
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs

      # 테스트
      - run: flutter test

      # Android Keystore
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SECRET_ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.SECRET_ANDROID_KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.SECRET_ANDROID_KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.SECRET_ANDROID_KEYSTORE_ALIAS }}
          KEY_PROPERTIES_PATH: android/app/keystore/key.properties
        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d -o key.jks < keystore-b64.txt
             mv key.jks android/app/keystore

          {
            echo "storePassword=$KEYSTORE_PASSWORD"
            echo "keyPassword=$KEY_PASSWORD"
            echo "keyAlias=$KEYSTORE_ALIAS"
            echo "storeFile=../app/keystore/key.jks"
          } > $KEY_PROPERTIES_PATH

      # 배포
      - name: Android deploy
        env:
          SECRET_ANDROID_JSON_KEY: ${{ secrets.SECRET_ANDROID_JSON_KEY }}
        run: |
          cd android
          fastlane android deploy

      # 배포
      - name: iOS Deploy
        run: |
          cd ios
          fastlane ios deploy
