name: Android Prod Deploy

on:
  push:
    branches: [ main, feature/ci-cd ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: Younggun-Kim/Github_Actions_Flutter_Setup@v1
    secrets:
      SECRET_GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}

  deploy:
    needs: setup
    runs-on: macos-latest
    steps:
      # Android Keystore
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SECRET_ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.SECRET_ANDROID_KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.SECRET_ANDROID_KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.SECRET_ANDROID_KEYSTORE_ALIAS }}
          KEY_PROPERTIES_PATH: android/app/keystore/key.properties
        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d -o key.jks < keystore-b64.txt
             mv key.jks android/app/keystore

          {
            echo "storePassword=$KEYSTORE_PASSWORD"
            echo "keyPassword=$KEY_PASSWORD"
            echo "keyAlias=$KEYSTORE_ALIAS"
            echo "storeFile=../app/keystore/key.jks"
          } > $KEY_PROPERTIES_PATH

      - name: Decode and save Google Play key
        run: |
          echo "${{ secrets.SECRET_ANDROID_JSON_KEY }}" | base64 -d > android/fastlane/key.json

      # 배포
      - name: Android deploy
        run: |
          cd android
          fastlane android deploy
