name: iOS Prod Deploy

on:
  push:
    branches: [ main, feature/ci-cd ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository  # 이 부분 추가
        uses: actions/checkout@v4
        with:
          submoddules: ${{ inputs.submodules }}
          token: ${{ inputs.github-token }}

      - name: Environment Setup
        uses: ./.github/workflows/flutter-setup.yml
        with:
          github-token: ${{ secrets.SECRET_GITHUB_TOKEN }}

      - name: iOS Deploy
        env:
          IOS_MATCH_GITHUB_URL: ${{ secrets.IOS_MATCH_GITHUB_URL }}
          IOS_GITHUB_BASIC_AUTH: ${{ secrets.IOS_GITHUB_BASIC_AUTH }}
          IOS_APPSTORE_TEAM_ID: ${{ secrets.IOS_APPSTORE_TEAM_ID }}
          IOS_APPSTORE_ITC_TEAM_ID: ${{ secrets.IOS_APPSTORE_ITC_TEAM_ID }}
          IOS_APPLE_ID: ${{ secrets.IOS_APPLE_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
        run: |
          cd ios
          fastlane ios deploy
