name: F-Lab flutter-withu Prod Deploy

on:
  push:
    branches: [ feature/ci-cd ]

# 동시성 설정 추가
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_prod:
    runs-on: macos-latest
    steps:
      # 기본 저장소 체크아웃
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submoddules: true
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}

      # Brew 설정
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      # Java 17 설정
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # fastlane 설치
      - name: Setup Fastlane
        run: |
          brew install fastlane
          gem install bundler

      # Flutter 설정
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      # 테스트
      - run: flutter test

      # 배포
      - name: iOS Deploy
        env:
          IOS_MATCH_GITHUB_URL: ${{ secrets.IOS_MATCH_GITHUB_URL }}
          IOS_GITHUB_BASIC_AUTH: ${{ secrets.IOS_GITHUB_BASIC_AUTH }}
          IOS_APPSTORE_TEAM_ID: ${{ secrets.IOS_APPSTORE_TEAM_ID }}
          IOS_APPSTORE_ITC_TEAM_ID: ${{ secrets.IOS_APPSTORE_ITC_TEAM_ID }}
          IOS_APPLE_ID: ${{ secrets.IOS_APPLE_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
        run: |
          cd ios
          fastlane ios deploy
